### PR TITLE
feat: Harvest should monitor ONTAP sensors

### PR DESCRIPTION
**Pull request by cgrinds**

### CODE REVIEW

**Comment by cgrinds** [comment]
```
sensor_threshold_status{datacenter="DC_002",cluster="umeng-aff300-05-06",discrete_state="normal",discrete_value="OK",node="umeng-aff300-05",sensor="PSU1 Fan2 Fault",type="discrete",threshold_state="normal"} 1
sensor_discrete_status{datacenter="DC_002",cluster="umeng-aff300-05-06",discrete_state="normal",discrete_value="OK",node="umeng-aff300-05",sensor="PSU1 Fan2 Fault",type="discrete",threshold_state="normal"} 1
sensor_threshold_status{datacenter="DC_002",cluster="umeng-aff300-05-06",discrete_value="OK",node="umeng-aff300-05",sensor="PSU1 Over Volt",type="discrete",threshold_state="normal",discrete_state="normal"} 1
sensor_discrete_status{datacenter="DC_002",cluster="umeng-aff300-05-06",discrete_value="OK",node="umeng-aff300-05",sensor="PSU1 Over Volt",type="discrete",threshold_state="normal",discrete_state="normal"} 1
sensor_threshold_status{datacenter="DC_002",cluster="umeng-aff300-05-06",node="umeng-aff300-06",sensor="Ambient Temp 1",type="thermal",threshold_state="normal",unit="C",warning_high="47",warning_low="5"} 1
sensor_discrete_status{datacenter="DC_002",cluster="umeng-aff300-05-06",node="umeng-aff300-06",sensor="Ambient Temp 1",type="thermal",threshold_state="normal",unit="C",warning_high="47",warning_low="5"} 0
```

**Review by Hardikl — APPROVED** [review]

**Review by rahulguptajss — DISMISSED** [review]

**Comment by hashi825** [comment]
my only input is I'd name the object environment_sensor in case there is any collision with other exporters out there since sensor is quite generic for a timeseries name, other than that looks good I've been currently using this as a custom template for a while now with no issues.

**Comment by cgrinds** [comment]
Appreciate the feedback. Good suggestion, change made.

```
# HELP environment_sensor_threshold_status Metric for environment_sensor
# TYPE environment_sensor_threshold_status gauge
environment_sensor_threshold_status{datacenter="openlab",cluster="umeng-aff300-05-06",site="munich",discrete_value="OK",node="umeng-aff300-06",sensor="PSU1 FAULT",type="discrete",threshold_state="normal",discrete_state="normal"} 1
# HELP environment_sensor_discrete_status Metric for environment_sensor
# TYPE environment_sensor_discrete_status gauge
environment_sensor_discrete_status{datacenter="openlab",cluster="umeng-aff300-05-06",site="munich",discrete_value="OK",node="umeng-aff300-06",sensor="PSU1 FAULT",type="discrete",threshold_state="normal",discrete_state="normal"} 1
# HELP environment_sensor_critical_low Metric for environment_sensor
# TYPE environment_sensor_critical_low gauge
environment_sensor_critical_low{datacenter="openlab",cluster="umeng-aff300-05-06",site="munich",unit="C",warning_high="60",warning_low="5",node="umeng-aff300-05",sensor="PCI Slot Temp",type="thermal",threshold_state="normal"} 0
# HELP environment_sensor_threshold_value Metric for environment_sensor
```

**Comment by hashi825** [comment]
I also used only one value mapping in my template

```yaml
plugins:
  - LabelAgent:
    value_to_num: status threshold_state normal `0`
```
This is due to non discrete sensors and normal sensors all having a threshold-sensor-state field in the API, there's no added value of having 2 different status metrics exported and the discrete state is  being exported as a label anyway, so this makes it available as part of alerting/querying etc.

**Review by Hardikl — APPROVED** [review]

**Pull request merged**
