### PR TITLE
[Merge only post release] update change log for 21.05.2

### PR DESCRIPTION
**Pull request by rahulguptajss**

### CODE REVIEW

**Review by ruanruijuan — COMMENTED** [review]
- About "Handle special characters in passwords", change to "Handle special characters in cluster credentials".
- do we want to specifically call out that we documented the capacity? I'm fine either way.

**Comment by rahulguptajss** [comment]
> * About "Handle special characters in passwords", change to "Handle special characters in cluster credentials".
> * do we want to specifically call out that we documented the capacity? I'm fine either way.

Updated password comment.
capacity documentation is now removed. @ruanruijuan you may want to review again as Chris udated changelog with better wording.

**Review by ruanruijuan — COMMENTED** [review]
"Performance metrics don't display volume name" -> "Performance metrics don't display volume names".

**Review by ruanruijuan — DISMISSED** [review]

**Comment by rahulguptajss** [comment]
> "Performance metrics don't display volume name" -> "Performance metrics don't display volume names".

done.

**Comment by rahulguptajss** [comment]
New PR @ https://github.com/NetApp/harvest/pull/114 due to release branch name change

**Pull request closed without merging**
