### PR TITLE
feat: data protection dashboard - part1 - snapshots

### PR DESCRIPTION
**Pull request by Hardikl**
UM screen:
image

Harvest screen:
image

Notes:
- MDV volumes are skipped in this dashboard
- counts are matching if we put aside the flex-constituents from harevst
- UM shows count on hover, we always show on bar

Open issue:
1. UM don't show flexgroup constituents, where as harvest convert the style to flexgroup and show them 
2. grafana some how not able to show bar when value is 0, working on that

### CODE REVIEW

**Comment by Hardikl** [comment]
image

Showing 0 in bar chart is done.

UM screen
image

**Review by cgrinds — COMMENTED** [review]
Nice job @Hardikl 
Can you remove the empty file `conf/zapi/cdot/9.8.0/failover.yaml`

The addition of the snapshot plugin will increase the response time of Zapi Volume. Any sense on how much? Volume is already one of the slower objects to query.

**Comment by Hardikl** [comment]
image

image

**Comment by Hardikl** [comment]
Removed conf/zapi/cdot/9.8.0/failover.yaml.
The addition of the snapshot plugin will increase the response time of Zapi Volume. Any sense on how much? --> Not yet calculated, Will update soon with detail.

**Review by rahulguptajss — APPROVED** [review]

**Comment by Hardikl** [comment]
image

image

**Comment by Hardikl** [comment]
Snapmirror related changes are planned for dashboard work for SM metrics.

**Comment by Hardikl** [comment]
image
 
image

**Review by cgrinds — APPROVED** [review]
very nice @Hardikl

**Comment by rahulguptajss** [comment]
need conflict resolve for dashboard_test

**Review by rahulguptajss — APPROVED** [review]

**Pull request merged**
