### PR TITLE
Volume dashboard select option

### PR DESCRIPTION
**Pull request by Hardikl**
supporting filter based on the chosen volume in volume dashboard.

Graphs:
These are the current numbers/graphs which supports volume filter:
- Average latency [number]
- Throughput [number]
- Total iops [number]
- Average latency [graph]
- Total average throughput [graph]
- Total iops [graph]
- volumes in cluster [table]

These are cluster scope graphs and not supporting filter on svm and volume: NO CHANGE HERE
- read latency
- read throughput
- read iops
- write latency
- write throughput
- write iops

Also, there is typo in write throughput graph [changed form read to write].

Grafana: http://10.249.24.71:3000/d/mRFX09Rnk/netapp-detail-volume?orgId=1&refresh=1m&var-Datacenter=DC-03&var-Cluster=F8080-32-25&var-SVM=All&var-Volume=MDV_CRS_d33421f0984011eb814a00a0986abd71_B&var-TopResources=5

### CODE REVIEW

**Review by vgratian — APPROVED** [review]
thanks, good job!

**Review by cgrinds — APPROVED** [review]

**Comment by cgrinds** [comment]
Nice job @Hardikl!

**Comment by florianmulatz** [comment]
> supporting filter based on the chosen volume in volume dashboard.
> 
> Graphs:
> These are the current numbers/graphs which supports volume filter:
> 
> * Average latency [number]
> * Throughput [number]
> * Total iops [number]
> * Average latency [graph]
> * Total average throughput [graph]
> * Total iops [graph]
> * volumes in cluster [table]
> 
> These are cluster scope graphs and not supporting filter on svm and volume: NO CHANGE HERE
> 
> * read latency
> * read throughput
> * read iops
> * write latency
> * write throughput
> * write iops
> 
> Also, there is typo in write throughput graph [changed form read to write].
> 
> Grafana: http://10.249.24.71:3000/d/mRFX09Rnk/netapp-detail-volume?orgId=1&refresh=1m&var-Datacenter=DC-03&var-Cluster=F8080-32-25&var-SVM=All&var-Volume=MDV_CRS_d33421f0984011eb814a00a0986abd71_B&var-TopResources=5

Regarding the graphs not supporting volume selection. Does this mean that there is not the right data coming from the database? Because this was working on old Harvest (1.6 - nabox) without any problems.

Cheers

**Comment by Hardikl** [comment]
We have made required changes, so now all graphs support filter based on svm and volume selection in volume dashboard. It was done here: https://github.com/NetApp/harvest/pull/221

**Pull request merged**
