### PR TITLE
Make vendored copy of dependencies

### PR DESCRIPTION
**Pull request by chrishenzie**
**NOTE:** I have not yet signed a CCLA, working on this.

See https://github.com/NetApp/harvest/issues/27 for context. This can assist with improving build times and reducing build flakiness (this usually is more impactful once there's more dependencies).

To repro, I ran `go mod vendor && go mod tidy`.

### CODE REVIEW

**Comment by cgrinds** [comment]
Thanks Chris! - Looks good, please sign CCLA

**Comment by chrishenzie** [comment]
Hello @cgrinds , I've signed the CCLA, hopefully the bot will show it on file soon, thank you!

@cla-bot check

**Comment by cgrinds** [comment]
Thanks @chrishenzie I'll check with legal

**Comment by cgrinds** [comment]
@cla-bot check

**Review by cgrinds — APPROVED** [review]
Thanks @chrishenzie

**Pull request merged**
