### PR TITLE
fix: dashboard changes for light theme

### PR DESCRIPTION
**Pull request by Hardikl**
Compliance dashboard
Before changes:
image

image

After changes:
image

image

Security dashboard
before changes:
image

image

after changes:
image

image

### CODE REVIEW

**Comment by Hardikl** [comment]
Covered
- NTP server number higher as 3 is Compliance
- Datacenter variable is sorted

**Comment by Hardikl** [comment]
> Atleast the first column should have the green sign?

Discussed in call, we are good with only ❌ in first column.

**Comment by Hardikl** [comment]
> Also keeping cross sign before text changes the indentation of records without any sign

Discussed in call, we will go ahead with this indentation for now and based on the customer's feedback, we will revisit this.

**Comment by cgrinds** [comment]
nice job @Hardikl

**Review by cgrinds — APPROVED** [review]

**Pull request merged**
