### PR TITLE
chore: update prometheus version v2.55.0 (#3223)

### PR DESCRIPTION
**Pull request by embusalacchi**

### CODE REVIEW

**Comment by cgrinds** [comment]
Thanks @embusalacchi. Version `v2.55.0` of Prometheus passes our CI. Have you been running with this locally, and if so, any issues when upgrading from version `2.33.1`?

**Comment by embusalacchi** [comment]
> Thanks @embusalacchi. Version `v2.55.0` of Prometheus passes our CI. Have you been running with this locally, and if so, any issues when upgrading from version `2.33.1`?

I have been running it in our production environment without any issues for the past 24 hours.  If you want I can check back in after a week but so far so good.  Is there something specific I can check for you?  I would be glad to look into it more.

**Comment by cgrinds** [comment]
We're still going through the cumulative change logs to better understand the scope of changes. There are several 😀. 

In terms of things to check:
- metrics are being scrapped
- historical metrics are still available
- dashboards that you use continue to work

I've also updated some of our internal systems and we'll check the above things on our end too.

Yes, plus report back with positive or negative impressions next week. Thanks!

**Comment by cgrinds** [comment]
Upgrading Prometheus to v2.55.0 uncovered a minor bug in Harvest that is fixed in #3230 and future Prometheus `warn|error` log messages will be discovered in CI via #3232

**Review by cgrinds — APPROVED** [review]

**Review by Hardikl — APPROVED** [review]

**Comment by cgrinds** [comment]
hi @embusalacchi any impressions on how version `2.55.0` of Prometheus has been running in your environment per https://github.com/NetApp/harvest/pull/3226#issuecomment-2433037830.

**Comment by embusalacchi** [comment]
> hi @embusalacchi any impressions on how version `2.55.0` of Prometheus has been running in your environment per [#3226 (comment)](https://github.com/NetApp/harvest/pull/3226#issuecomment-2433037830).

I haven't seen any issues in our environment.  I haven't done a deep dive but our normal everyday usage hasn't seen anything different.

**Comment by cgrinds** [comment]
Appreciate the feedback and PR

**Pull request merged**
